---
# This will install nrpe

- name: install nrpe
  copy: src=nrpe dest=/usr/local/nrpe

- name: nrpe etc.d config
  copy: src=etc.d dest=/usr/local/nrpe/etc.d

- name: nrpe etc config
  copy: src=nrpe.cfg dest=/usr/local/nrpe/etc

- name: chown nrpe user
  shell: chown naigos.nagios -R /usr/local/nrpe
